server:
  contextPath: /ehr
  port: 8090
  sessionTimeout:  30000000

multipart:
  maxFileSize: 50Mb
  maxRequestSize: 50Mb

fast-dfs:
  pool:
    init-size: 5
    max-size: 20
    wait-time: 500
  connect-timeout: 2
  network-timeout: 30
  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890

permissions:
  info: admin

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
app:
  baseClientId: zkGuSIm2Fg  # 【基础信息管理】应用
  qcReportClientId: 2YTOSRI0tw
  resourceBrowseClientId: W8RDizgDIB
  browseClientId: uzs5G0HgTp
  oauth2InnerUrl: http://172.19.103.73:10260/
  oauth2OuterUrl: http://27.154.233.186:10260/  #厦门-认证外网
service-gateway:
  username: user
  password: eureka
  url: http://172.19.103.73:10000/api/v1.0/admin
  adminInnerUrl: http://172.19.103.73:10000
  stdurl: http://172.19.103.73:10000/api/v1.0/admin/std
  versionurl: http://172.19.103.73:10000/api/v1.0/admin/version
  cdatypeurl: http://172.19.103.73:10000/api/v1.0/admin/cda_type
  stdsourceurl: http://172.19.103.73:10000/api/v1.0/admin/standard_source
  adaption: http://172.19.103.73:10000/api/v1.0/adapter
  template: http://172.19.103.73:10000/api/v1.0/template
  standard: http://172.19.103.73:10000/api/v1.0/std
  browseClientUrl: http://192.168.1.221:8010/profile/browser
  browseClientOutSizeUrl: http://27.154.233.186:9480/profile/browser
  profileurl: http://172.19.103.74:9009/api/v1.0
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
std:
  version: 59083976eebd

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
app:
  baseClientId: zkGuSIm2Fg  # 【基础信息管理】应用
  qcReportClientId: 2YTOSRI0tw
  resourceBrowseClientId: W8RDizgDIB
  browseClientId: uzs5G0HgTp
  oauth2InnerUrl: http://172.19.103.73:10260/
  oauth2OuterUrl: http://172.19.103.73:10260/
service-gateway:
  username: user
  password: eureka
  url: http://172.19.103.58:10000/api/v1.0/admin
  adminInnerUrl: http://172.19.103.58:10000
  stdurl: http://172.19.103.58:10000/api/v1.0/admin/std
  versionurl: http://172.19.103.58:10000/api/v1.0/admin/version
  cdatypeurl: http://172.19.103.58:10000/api/v1.0/admin/cda_type
  stdsourceurl: http://172.19.103.58:10000/api/v1.0/admin/standard_source
  adaption: http://172.19.103.58:10000/api/v1.0/adapter
  template: http://172.19.103.58:10000/api/v1.0/template
  standard: http://172.19.103.58:10000/api/v1.0/std
  browseClientUrl: http://172.19.103.58:8010/profile/browser
  browseClientOutSizeUrl: http://172.19.103.58:8010/profile/browser
  profileurl: http://172.19.103.58:9009/api/v1.0
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
std:
  version: 59083976eebd

---
spring:
  profiles: prod_fz
  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
app:
  baseClientId: zkGuSIm2Fg  # 【基础信息管理】应用
  qcReportClientId: 2YTOSRI0tw
  resourceBrowseClientId: W8RDizgDIB
  browseClientId: uzs5G0HgTp
  oauth2InnerUrl: http://11.1.2.16:10260/
  oauth2OuterUrl: http://11.1.2.16:10260/
service-gateway:
  username: user
  password: eureka
  url: http://11.1.2.13:10000/api/v1.0/admin
  adminInnerUrl: http://11.1.2.13:10000
  stdurl: http://11.1.2.13:10000/api/v1.0/admin/std
  versionurl: http://11.1.2.13:10000/api/v1.0/admin/version
  cdatypeurl: http://11.1.2.13:10000/api/v1.0/admin/cda_type
  stdsourceurl: http://11.1.2.13:10000/api/v1.0/admin/standard_source
  adaption: http://11.1.2.13:10000/api/v1.0/adapter
  template: http://11.1.2.13:10000/api/v1.0/template
  standard: http://11.1.2.13:10000/api/v1.0/std
  browseClientUrl: http://11.1.2.16:8010/profile/browser
  browseClientOutSizeUrl: http://11.1.2.16:8010/profile/browser
  profileurl: http://11.1.2.14:9009/api/v1.0
fast-dfs:
  tracker-server: 11.1.2.9:22122
  public-server: http://11.1.2.9:80
std:
  version: 59083976eebd
logging:
    config: classpath:logback-spring.xml

---
spring:
  profiles: prod_sr
  datasource:
    url: jdbc:mysql://10.176.97.9:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
app:
  baseClientId: zkGuSIm2Fg  # 【基础信息管理】应用
  qcReportClientId: 2YTOSRI0tw
  resourceBrowseClientId: W8RDizgDIB
  browseClientId: uzs5G0HgTp
  oauth2InnerUrl: http://10.176.97.10:10260/
  oauth2OuterUrl: http://171.35.109.35:1235/  #上饶-认证外网
service-gateway:
  username: user
  password: eureka
  url: http://10.176.97.10:10000/api/v1.0/admin
  adminInnerUrl: http://10.176.97.10:10000
  stdurl: http://10.176.97.10:10000/api/v1.0/admin/std
  versionurl: http://10.176.97.10:10000/api/v1.0/admin/version
  cdatypeurl: http://10.176.97.10:10000/api/v1.0/admin/cda_type
  stdsourceurl: http://10.176.97.10:10000/api/v1.0/admin/standard_source
  adaption: http://10.176.97.10:10000/api/v1.0/adapter
  template: http://10.176.97.10:10000/api/v1.0/template
  standard: http://10.176.97.10:10000/api/v1.0/std
  browseClientUrl: http://10.176.97.11:8010/profile/browser
  browseClientOutSizeUrl: http://171.35.109.35:1235/profile/browser
  profileurl: http://10.176.97.12:9009/api/v1.0
fast-dfs:
  tracker-server: 10.176.97.5:22122
  public-server: http://10.176.97.5:8888
std:
  version: 59083976eebd


---
spring:
  profiles: prod_fzzy
  datasource:
    url: jdbc:mysql://100.100.1.159:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
app:
  baseClientId: zkGuSIm2Fg  # 【基础信息管理】应用
  qcReportClientId: 2YTOSRI0tw
  resourceBrowseClientId: W8RDizgDIB
  browseClientId: uzs5G0HgTp
  oauth2InnerUrl: http://100.100.1.162:10260/
  oauth2OuterUrl: http://100.100.1.162:10260/  #上饶-认证外网
service-gateway:
  username: user
  password: eureka
  url: http://100.100.1.162:10000/api/v1.0/admin
  adminInnerUrl: http://100.100.1.162:10000
  stdurl: http://100.100.1.162:10000/api/v1.0/admin/std
  versionurl: http://100.100.1.162:10000/api/v1.0/admin/version
  cdatypeurl: http://100.100.1.162:10000/api/v1.0/admin/cda_type
  stdsourceurl: http://100.100.1.162:10000/api/v1.0/admin/standard_source
  adaption: http://100.100.1.162:10000/api/v1.0/adapter
  template: http://100.100.1.162:10000/api/v1.0/template
  standard: http://100.100.1.162:10000/api/v1.0/std
  browseClientUrl: http://100.100.1.163:8010/profile/browser
  browseClientOutSizeUrl: http://100.100.1.163:8010/profile/browser
  profileurl: http://100.100.1.164:9009/api/v1.0
fast-dfs:
  tracker-server: 100.100.1.157:22122
  public-server: http://100.100.1.157:8888
std:
  version: 59083976eebd

---
spring:
  profiles: prod_srformal
  datasource:
    url: jdbc:mysql://192.168.210.3:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
app:
  baseClientId: zkGuSIm2Fg  # 【基础信息管理】应用
  qcReportClientId: 2YTOSRI0tw
  resourceBrowseClientId: W8RDizgDIB
  browseClientId: uzs5G0HgTp
  oauth2InnerUrl: http://192.168.220.84:10000/authentication/
  oauth2OuterUrl: http://223.84.134.42:1235/
service-gateway:
  username: user
  password: eureka
  url: http://192.168.220.84:10000/api/v1.0/admin
  adminInnerUrl: http://192.168.220.84:10000
  stdurl: http://192.168.220.84:10000/api/v1.0/admin/std
  versionurl: http://192.168.220.84:10000/api/v1.0/admin/version
  cdatypeurl: http://192.168.220.84:10000/api/v1.0/admin/cda_type
  stdsourceurl: http://192.168.220.84:10000/api/v1.0/admin/standard_source
  adaption: http://192.168.220.84:10000/api/v1.0/adapter
  template: http://192.168.220.84:10000/api/v1.0/template
  standard: http://192.168.220.84:10000/api/v1.0/std
  browseClientUrl: http://192.168.220.72:8010/profile/browser
  browseClientOutSizeUrl: http://223.84.134.42:1234/profile/browser
  profileurl: http://192.168.200.68:9009/api/v1.0
fast-dfs:
  tracker-server: 192.168.50.116:22122,192.168.50.119:22122
  public-server: http://192.168.50.37:8888
std:
  version: 59083976eebd
