server:
  contextPath: /ehr
  port: 8090
  sessionTimeout:  30000000

multipart:
  maxFileSize: 50Mb
  maxRequestSize: 50Mb

fast-dfs:
  pool:
    init-size: 5
    max-size: 20
    wait-time: 500
  connect-timeout: 2
  network-timeout: 30

  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890

permissions:
  info: admin

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: weifuwu
    password: weifuwu
app:
  baseClientId: zkGuSIm2Fg  # 【基础信息管理】应用
  qcReportClientId: 2YTOSRI0tw
  resourceBrowseClientId: W8RDizgDIB
  browseClientId: uzs5G0HgTp
  oauth2authorize: http://172.19.103.73:10260/
  oauth2OutSize: http://27.154.233.186:10260/  #厦门-认证外网
service-gateway:
  username: user
  password: eureka
  url: http://localhost:10000/api/v1.0/admin
  stdurl: http://172.19.103.73:10000/api/v1.0/admin/std
  versionurl: http://172.19.103.73:10000/api/v1.0/admin/version
  cdatypeurl: http://172.19.103.73:10000/api/v1.0/admin/cda_type
  stdsourceurl: http://172.19.103.73:10000/api/v1.0/admin/standard_source
  adaption: http://172.19.103.73:10000/api/v1.0/adapter
  template: http://172.19.103.73:10000/api/v1.0/template
  standard: http://172.19.103.73:10000/api/v1.0/std
  browseClientUrl: http://192.168.1.221:8010/ehr/browser
  browseClientOutSizeUrl: http://27.154.233.186:9480/ehr/browser
  profileurl: http://172.17.110.227:9009/api/v1.0
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
std:
  version: 59083976eebd

---
spring:
  profiles: alpha
  datasource:
    url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: ha
    password: ha
app:
  baseClientId: zkGuSIm2Fg  # 【基础信息管理】应用
  qcReportClientId: 2YTOSRI0tw
  resourceBrowseClientId: W8RDizgDIB
  browseClientId: uzs5G0HgTp
  oauth2authorize: http://192.168.1.221:10260/
  oauth2OutSize: http://192.168.1.221:10260/
service-gateway:
  username: user
  password: eureka
  url: http://localhost:10000/api/v1.0/admin
  stdurl: http://localhost:10000/api/v1.0/admin/std
  versionurl: http://localhost:10000/api/v1.0/admin/version
  cdatypeurl: http://localhost:10000/api/v1.0/admin/cda_type
  stdsourceurl: http://localhost:10000/api/v1.0/admin/standard_source
  adaption: http://localhost:10000/api/v1.0/adapter
  template: http://localhost:10000/api/v1.0/template
  standard: http://localhost:10000/api/v1.0/std
  browseClientUrl: http://192.168.1.221:8010/ehr/browser
  browseClientOutSizeUrl: http://192.168.1.221:8010/ehr/browser
  profileurl: http://localhost:9009/api/v1.0
fast-dfs:
  tracker-server: 172.19.103.54:22122
std:
  version: 59083976eebd

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: chenweishan
    password: chenweishan
app:
  baseClientId: zkGuSIm2Fg  # 【基础信息管理】应用
  qcReportClientId: 2YTOSRI0tw
  resourceBrowseClientId: W8RDizgDIB
  browseClientId: uzs5G0HgTp
  oauth2authorize: http://172.19.103.73:10260/
  oauth2OutSize: http://172.19.103.73:10260/
service-gateway:
  username: user
  password: eureka
  url: http://172.19.103.73:10000/api/v1.0/admin
  stdurl: http://172.19.103.73:10000/api/v1.0/admin/std
  versionurl: http://172.19.103.73:10000/api/v1.0/admin/version
  cdatypeurl: http://172.19.103.73:10000/api/v1.0/admin/cda_type
  stdsourceurl: http://172.19.103.73:10000/api/v1.0/admin/standard_source
  adaption: http://172.19.103.73:10000/api/v1.0/adapter
  template: http://172.19.103.73:10000/api/v1.0/template
  standard: http://172.19.103.73:10000/api/v1.0/std
  browseClientUrl: http://172.19.103.73:8010/ehr/browser
  browseClientOutSizeUrl: http://172.19.103.73:8010/ehr/browser
  profileurl: http://172.19.103.73:9009/api/v1.0
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
std:
  version: 59083976eebd

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: ha
    password: ha
app:
  baseClientId: zkGuSIm2Fg  # 【基础信息管理】应用
  qcReportClientId: 2YTOSRI0tw
  resourceBrowseClientId: W8RDizgDIB
  browseClientId: uzs5G0HgTp
  oauth2authorize: http://192.168.1.221:10260/
  oauth2OutSize: http://192.168.1.221:10260/
service-gateway:
  username: user
  password: eureka
  url: http://11.1.2.21:10000/api/v1.0/admin
  stdurl: http://11.1.2.21:10000/api/v1.0/admin/std
  versionurl: http://11.1.2.21:10000/api/v1.0/admin/version
  cdatypeurl: http://11.1.2.21:10000/api/v1.0/admin/cda_type
  stdsourceurl: http://11.1.2.21:10000/api/v1.0/admin/standard_source
  adaption: http://11.1.2.21:10000/api/v1.0/adapter
  template: http://11.1.2.21:10000/api/v1.0/template
  standard: http://11.1.2.21:10000/api/v1.0/std
  browseClientUrl: http://192.168.1.221:8010/ehr/browser
  browseClientOutSizeUrl: http://192.168.1.221:8010/ehr/browser
  profileurl: http://11.1.2.21:9009/api/v1.0
fast-dfs:
  tracker-server: 11.1.2.9:22122
std:
  version: 59083976eebd
logging:
    config: classpath:logback-spring.xml

---
spring:
  profiles: prod_fz
  datasource:
    url: jdbc:mysql://192.168.135.39:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: sr_healtharchive
    password: data!@)1
app:
  baseClientId: zkGuSIm2Fg  # 【基础信息管理】应用
  qcReportClientId: 2YTOSRI0tw
  resourceBrowseClientId: W8RDizgDIB
  browseClientId: uzs5G0HgTp
  oauth2authorize: http://192.168.135.35:10260/
  oauth2OutSize: http://192.168.135.35:10260/
service-gateway:
  username: user
  password: eureka
  url: http://192.168.135.31:10000/api/v1.0/admin
  stdurl: http://192.168.135.31:10000/api/v1.0/admin/std
  versionurl: http://192.168.135.31:10000/api/v1.0/admin/version
  cdatypeurl: http://192.168.135.31:10000/api/v1.0/admin/cda_type
  stdsourceurl: http://192.168.135.31:10000/api/v1.0/admin/standard_source
  adaption: http://192.168.135.31:10000/api/v1.0/adapter
  template: http://192.168.135.31:10000/api/v1.0/template
  standard: http://192.168.135.31:10000/api/v1.0/std
  browseClientUrl: http://192.168.135.34:8010/ehr/browser
  browseClientOutSizeUrl: http://192.168.135.34:8010/ehr/browser
  profileurl: http://192.168.135.32:9009/api/v1.0
fast-dfs:
  tracker-server: 192.168.135.42:22122
  public-server: http://192.168.135.42:22122
std:
  version: 59083976eebd
logging:
    config: classpath:logback-spring.xml

---
spring:
  profiles: prod_sr
  datasource:
    url: jdbc:mysql://10.176.97.9:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: healthcloud
    password: GP8Qz4qU
app:
  baseClientId: zkGuSIm2Fg  # 【基础信息管理】应用
  qcReportClientId: 2YTOSRI0tw
  resourceBrowseClientId: W8RDizgDIB
  browseClientId: uzs5G0HgTp
  oauth2authorize: http://10.176.97.10:10260/
  oauth2OutSize: http://10.176.97.10:10260/  #上饶-认证外网
service-gateway:
  username: user
  password: eureka
  url: http://10.176.97.10:10000/api/v1.0/admin
  stdurl: http://10.176.97.10:10000/api/v1.0/admin/std
  versionurl: http://10.176.97.10:10000/api/v1.0/admin/version
  cdatypeurl: http://10.176.97.10:10000/api/v1.0/admin/cda_type
  stdsourceurl: http://10.176.97.10:10000/api/v1.0/admin/standard_source
  adaption: http://10.176.97.10:10000/api/v1.0/adapter
  template: http://10.176.97.10:10000/api/v1.0/template
  standard: http://10.176.97.10:10000/api/v1.0/std
  browseClientUrl: http://10.176.97.11:8010/ehr/browser
  browseClientOutSizeUrl: http://10.176.97.11:8010/ehr/browser
  profileurl: http://10.176.97.12:9009/api/v1.0
fast-dfs:
  tracker-server: 10.176.97.5:22122
  public-server: http://10.176.97.5:80
std:
  version: 59083976eebd
